#include "convolution_pass.hpp"

#include <algorithm>
#include <cstring>

namespace shadebug {

namespace {

struct KernelUniforms {
    float values[KernelData::MaxValues];
    uint32_t size;
    float normalization;

    // Keep the struct comfortably aligned for GPU constant-buffer rules.
    float _padding[2];
};

static_assert(
    sizeof(KernelUniforms) % 16 == 0,
    "KernelUniforms should have 16-byte size alignment"
);

} // namespace

bool ConvolutionPass::init() {
    if (_initialized) {
        return true;
    }

    /*
        The shader is expected to be generated/loaded by the same mechanism
        currently used by shadebug for its other shaders.

        Replace this with your project's actual shader creation path.

        For example, if convolution_shader_desc() is generated by
        sokol-shdc:

            _shader = sg_make_shader(
                convolution_shader_desc(sg_query_backend())
            );
    */

    _shader = sg_make_shader(
        convolution_shader_desc(sg_query_backend())
    );

    if (!sg_query_shader_state(_shader).valid) {
        return false;
    }

    _pipeline = sg_make_pipeline(&(sg_pipeline_desc){
        .compute = true,
        .shader = _shader,
        .label = "shadebug-convolution-pipeline",
    });

    if (!sg_query_pipeline_state(_pipeline).valid) {
        sg_destroy_shader(_shader);
        _shader = {};
        return false;
    }

    /*
        Dynamic buffer containing the kernel matrix.

        We update this once per convolution dispatch.

        In the first implementation this could also be implemented as
        uniforms. Keeping it in a buffer gives us a straightforward path
        toward larger/more complex kernels later.
    */

    _kernel_buffer = sg_make_buffer(&(sg_buffer_desc){
        .size = sizeof(KernelUniforms),
        .usage = {
            .dynamic_update = true
        },
        .label = "shadebug-convolution-kernel-buffer",
    });

    if (!sg_query_buffer_state(_kernel_buffer).valid) {
        sg_destroy_pipeline(_pipeline);
        sg_destroy_shader(_shader);

        _pipeline = {};
        _shader = {};

        return false;
    }

    _initialized = true;
    return true;
}


void ConvolutionPass::shutdown() {
    if (!_initialized) {
        return;
    }

    if (sg_query_buffer_state(_kernel_buffer).valid) {
        sg_destroy_buffer(_kernel_buffer);
    }

    if (sg_query_pipeline_state(_pipeline).valid) {
        sg_destroy_pipeline(_pipeline);
    }

    if (sg_query_shader_state(_shader).valid) {
        sg_destroy_shader(_shader);
    }

    _kernel_buffer = {};
    _pipeline = {};
    _shader = {};

    _width = 0;
    _height = 0;

    _initialized = false;
}


bool ConvolutionPass::resize(int width, int height) {
    if (!_initialized) {
        return false;
    }

    if (width <= 0 || height <= 0) {
        return false;
    }

    if (_width == width && _height == height) {
        return true;
    }

    _width = width;
    _height = height;

    /*
        The actual intermediate texture allocation should probably live
        in RenderPipeline rather than ConvolutionPass.

        This method is intentionally left as the lifecycle hook so the
        pass can react to viewport changes.

        See the RenderPipeline example below.
    */

    return true;
}


void ConvolutionPass::apply(
    sg_view input,
    sg_view output,
    int width,
    int height,
    const KernelData& kernel
) {
    if (!_initialized) {
        return;
    }

    if (!input.id || !output.id) {
        return;
    }

    if (width <= 0 || height <= 0) {
        return;
    }

    const uint32_t size = std::clamp(
        kernel.size,
        1u,
        KernelData::MaxSize
    );

    KernelUniforms gpu_kernel{};

    gpu_kernel.size = size;

    gpu_kernel.normalization =
        kernel.normalization == 0.0f
            ? 1.0f
            : kernel.normalization;

    const uint32_t value_count = size * size;

    std::memcpy(
        gpu_kernel.values,
        kernel.values,
        sizeof(float) * value_count
    );

    /*
        Upload the matrix.

        sg_update_buffer() is intended for dynamic per-frame updates.
    */
    sg_update_buffer(
        _kernel_buffer,
        &gpu_kernel,
        sizeof(gpu_kernel)
    );

    /*
        Compute pass.
    */
    sg_begin_pass(&(sg_pass){
        .compute = true,
        .label = "shadebug-convolution-pass",
    });

    sg_apply_pipeline(_pipeline);

    /*
        The exact binding indices below should correspond to the shader:

            binding 0 -> input texture
            binding 1 -> output storage image
            binding 2 -> kernel buffer
    */

    sg_apply_bindings(&(sg_bindings){
        .views = {
            [0] = input,
            [1] = output,
            [2] = sg_make_view(&(sg_view_desc){
                .buffer = {
                    .buffer = _kernel_buffer,
                },
                .label = "shadebug-convolution-kernel-view",
            }),
        },
    });

    /*
        A 16x16 workgroup is a reasonable initial choice.

        The shader must contain:

            local_size_x = 16
            local_size_y = 16
    */

    constexpr int WorkgroupSize = 16;

    const int groups_x =
        (width + WorkgroupSize - 1) / WorkgroupSize;

    const int groups_y =
        (height + WorkgroupSize - 1) / WorkgroupSize;

    sg_dispatch(groups_x, groups_y, 1);

    sg_end_pass();
}

} // namespace shadebug
